
trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - doc/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects:  '**/*.csproj'
    verbosityRestore: Minimal
    noCache: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    projects: 'test/**/*.csproj'
    arguments: '-p:DebugType=Full -p:CoverageRoot="$(Build.ArtifactStagingDirectory)/results'
    testRunTitle: 'dotnet test'
    configuration: '$(buildConfiguration)'  
